### ISSUE TITLE
receiving exception: lateinit property scene has not been initialized on jvm on desktop

### ISSUE THREAD

**Issue by khebrati** [mahozad/comshot#1]
hi. I added your library from maven central to my app, and then I used the exact sample code in the repo somewhere in my app:
```kotlin
@Composable
fun composeToBitmap() {
    var screenshot by remember { mutableStateOf<ImageBitmap?>(null) }
    val composable: @Composable () -> Unit = remember {
        @Composable {
            Row {
                Text(text = "Hello")
                Text(text = "Meow!")
            }
        }
    }
    // You can also render your composable simply like this:
    // composable()
    Column {
        Button(onClick = { screenshot = captureToImage(composable) }) {
            Text(text = "Capture")
        }
        screenshot?.let {
            Image(
                bitmap = it,
                modifier = Modifier.width(200.dp),
                contentDescription = null
            )
        }
    }
}
```
but when I run the app, I get this exception:

Exception in thread "AWT-EventQueue-0" kotlin.UninitializedPropertyAccessException: lateinit property scene has not been initialized
	at androidx.compose.ui.test.SkikoComposeUiTest.getScene(ComposeUiTest.skikoMain.kt:134)
	at androidx.compose.ui.test.SkikoComposeUiTest.withScene(ComposeUiTest.skikoMain.kt:158)
	at androidx.compose.ui.test.SkikoComposeUiTest.access$withScene(ComposeUiTest.skikoMain.kt:88)
	at androidx.compose.ui.test.SkikoComposeUiTest$runTest$1.invoke(ComposeUiTest.skikoMain.kt:145)
	at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.skiko.kt:83)
	at androidx.compose.ui.test.SkikoComposeUiTest.runTest(ComposeUiTest.skikoMain.kt:144)
	at androidx.compose.ui.test.ComposeUiTest_skikoMainKt.runSkikoComposeUiTest-Cqks5Fs(ComposeUiTest.skikoMain.kt:75)
	at androidx.compose.ui.test.ComposeUiTest_skikoMainKt.runSkikoComposeUiTest-Cqks5Fs$default(ComposeUiTest.skikoMain.kt:63)
	at ir.mahozad.multiplatform.comshot.Comshot_desktopKt.captureToImage(Comshot.desktop.kt:45)
	at nikted.fitting.compose.kmp.presentation.clients.ClientsScreenKt.composeToBitmap$lambda$8$lambda$6$lambda$5(ClientsScreen.kt:315)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:991)
	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:984)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:258)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:672)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:549)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:571)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:950)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:798)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:326)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:312)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:187)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:106)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:114)
	at androidx.compose.ui.node.RootNodeOwner.onPointerInput(RootNodeOwner.skiko.kt:212)
	at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.processRelease(MultiLayerComposeScene.skiko.kt:321)
	at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.processPointerInputEvent(MultiLayerComposeScene.skiko.kt:236)
	at androidx.compose.ui.scene.BaseComposeScene$inputHandler$2.invoke(BaseComposeScene.skiko.kt:62)
	at androidx.compose.ui.scene.BaseComposeScene$inputHandler$2.invoke(BaseComposeScene.skiko.kt:62)
	at androidx.compose.ui.input.pointer.SyntheticEventSender.sendInternal(SyntheticEventSender.skiko.kt:175)
	at androidx.compose.ui.input.pointer.SyntheticEventSender.send(SyntheticEventSender.skiko.kt:79)
	at androidx.compose.ui.scene.ComposeSceneInputHandler.onPointerEvent-WlEVilQ(ComposeSceneInputHandler.skiko.kt:123)
	at androidx.compose.ui.scene.ComposeSceneInputHandler.onPointerEvent-BGSDPeU(ComposeSceneInputHandler.skiko.kt:89)
	at androidx.compose.ui.scene.BaseComposeScene.sendPointerEvent-BGSDPeU(BaseComposeScene.skiko.kt:185)
	at androidx.compose.ui.scene.ComposeScene.sendPointerEvent-BGSDPeU$default(ComposeScene.skiko.kt:186)
	at androidx.compose.ui.scene.ComposeSceneMediator_desktopKt.onMouseEvent-d-4ec7I(ComposeSceneMediator.desktop.kt:709)
	at androidx.compose.ui.scene.ComposeSceneMediator_desktopKt.access$onMouseEvent-d-4ec7I(ComposeSceneMediator.desktop.kt:1)
	at androidx.compose.ui.scene.ComposeSceneMediator.onMouseEvent(ComposeSceneMediator.desktop.kt:403)
	at androidx.compose.ui.scene.ComposeSceneMediator.access$onMouseEvent(ComposeSceneMediator.desktop.kt:102)
	at androidx.compose.ui.scene.ComposeSceneMediator$mouseListener$1.mouseReleased(ComposeSceneMediator.desktop.kt:234)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.scene.ComposeContainer$DesktopCoroutineExceptionHandler@6f632f41, androidx.compose.runtime.BroadcastFrameClock@3abf6839, StandaloneCoroutine{Cancelling}@46cbe0a9, FlushCoroutineDispatcher@5f75830a]

**Comment by mahozad** [comment]
Hello

Can you specify what version of kotlin and compose multiplatform you are using?
And your OS?

**Comment by khebrati** [comment]
kotlin = "2.0.0"
compose = "1.6.11"
I have tried it both on windows 10 and linux mint 2024 and got the same error. Also, my project is a compose multiplatform that targets jvm 17. I have tried using it both on common source set and jvmMain main source set and still got the same error.

**Comment by mahozad** [comment]
I've updated libraries and published version `0.2.0`. Will be available in a few hours.

Can you please check and see if the new version works for you?

**Comment by khebrati** [comment]
thanks! I'll check it tomorrow

**Comment by khebrati** [comment]
hello mahdi. I just checked the version 2 of your library on desktop and it works flawlessly! great job body. The only thing was I had to migrate our project from jvm 17 to jvm 21 because I was receiving an error indicating a library compiled with jvm 21 can not be run with jvm 17:
![image](https://github.com/mahozad/comshot/assets/131471493/86d6f61c-f6a0-48ed-b4bc-07da6c889acf)
but it was gone when I migrated our project to jvm 21. 
great job overall !

**Comment by khebrati** [comment]
There is yet another problem. The composable function that I am trying to take a screen shot of is a screen with a long height that is scrollable. I have noticed that no matter what composable function I pass to your library's "captureToImage" function, it will output an ImageBitmap with height : 768 and width: 1024. So in my case, to ImageBitmap lacks 70 percent of the composable height because it doesn't fit in 768 pixels! Is there any way we can change this? I mean, is it configurable in this version of your library? and if it's not, please guide me to the changes I can make to the source code to make this happen. thanks in advance!

**Comment by khebrati** [comment]
I just checked it in android and it's just fine. The function outputs the given compose in full resolution.

**Comment by mahozad** [comment]
Can you please create a new issue?

**Comment by khebrati** [comment]
of course
