### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skiko.redrawer.MetalRedrawer.setDisplaySyncEnabled(long, boolean)' 	at org.jetbrains.skiko.redrawer.MetalRedrawer.setDisplaySyncEnabled(Native Method)

### ISSUE THREAD

**Issue by Merati22** [mahozad/comshot#3]
Hello,
i added your library on my project like this in build.gradle.kt:

```kotlin
        jvmMain.dependencies {
            implementation(compose.desktop.common)
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(libs.sqlDelight.driver.sqlite)
            implementation(libs.ui.tooling.preview)
            implementation(libs.jSerialComm)
            implementation(libs.kernel)
            implementation(libs.layout)
            implementation(libs.io)
            implementation(libs.comshot)
        }

```

now when i run project in desktop-jvm i face this error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.jetbrains.skiko.redrawer.MetalRedrawer.setDisplaySyncEnabled(long, boolean)'
	at org.jetbrains.skiko.redrawer.MetalRedrawer.setDisplaySyncEnabled(Native Method)
	
my jvm version in android studio setting/gradle is 21 like this:

![Screenshot 2024-07-11 at 3 02 07 PM](https://github.com/mahozad/comshot/assets/85545518/49497181-19fb-40dc-ad64-680130a11011)

my compose version is 1.6.11 and my kotlin version is 2.0.0

my system is Mac mini M2 pro with Sonoma version of macOS

**Comment by mahozad** [comment]
Hello.

Thanks for raising the issue.

**Comment by Merati22** [comment]
i saw here you asked same question:
https://github.com/JetBrains/skiko/issues/872
how did you resolve the issue?

**Comment by mahozad** [comment]
Please try the solution in this comment: https://github.com/JetBrains/skiko/issues/872#issuecomment-1983356775

**Comment by Merati22** [comment]
i just solved it by adding this in build.gradle.kt :
```
        val desktopMain by getting {
            dependencies {
                // api(libs.androidx.ui.desktop)
                val osName = System.getProperty("os.name")
                val targetOs = when {
                    osName == "Mac OS X" -> "macos"
                    osName.startsWith("Win") -> "windows"
                    osName.startsWith("Linux") -> "linux"
                    else -> error("Unsupported OS: $osName")
                }

                val osArch = System.getProperty("os.arch")
                val targetArch = when (osArch) {
                    "x86_64", "amd64" -> "x64"
                    "aarch64" -> "arm64"
                    else -> error("Unsupported arch: $osArch")
                }

                val version = "0.8.9" // or any more recent version
                val target = "${targetOs}-${targetArch}"
                implementation("org.jetbrains.skiko:skiko-awt-runtime-$target:$version")
            }
        }
```
because it couldn't use skiko for macOs.
